import json

from grounding.verify import chunk_document, CHUNK_MAX_CHARS
from grounding.labelling import aggregate_label
from grounding.localise import best_span, span_from_chunk_index, section_char_ranges
from grounding.numeric_check import check_numeric_claim, Contradicted, format_mismatch_rationale
from grounding.provenance import ProvenanceRecorder


def label_claims(
    decomposed: list[dict], full_text: str, sections: list[dict], verifier_fn,
    recorder: ProvenanceRecorder | None = None, verifier_model: str = "unknown",
) -> list[dict]:
    """Wire decompose -> verify -> aggregate_label -> localise -> claim record.

    verifier_fn: callable(subclaim: str, chunks: list[str]) -> tuple[bool, float | None, int | None]
    Use make_minicheck_verifier() or make_claude_verifier() from grounding.verify.
    score/idx are None for verifiers with no per-chunk signal (Claude Haiku).

    The evidence span for a grounded/partial claim is resolved from the
    highest-scoring supported subclaim's verifier chunk index
    (span_from_chunk_index), falling back to best_span()'s keyword-overlap
    heuristic when no usable chunk index exists (Haiku verifier, or a chunk
    that doesn't overlap any section) -- never a hard failure or an empty
    span where one was previously found.

    A deterministic numeric-consistency check runs after aggregation: if the
    claim states a figure absent from its matched evidence, the label is
    downgraded (grounded -> unsupported, partial stays partial) and an
    honest, factual rationale is generated. This check is not part of the
    RAGTruth-validated verifier itself -- see numeric_check.py's docstring.

    recorder: when provided, wraps each claim's verify step in a PROV
    Activity (Agent = verifier_model) and records the verdict + a
    verify_signal Entity as generated by it. The evidence span, once
    resolved, is recorded as wasDerivedFrom the verify_signal -- never as
    something Verify itself `used`, since the span isn't known until after
    the verify loop's results are in hand. Default None preserves today's
    return shape and behaviour exactly -- no existing caller needs to change.
    """
    chunks = chunk_document(full_text, max_chars=CHUNK_MAX_CHARS)
    section_ranges = section_char_ranges(sections, full_text)
    out = []
    for i, dc in enumerate(decomposed):
        claim_id = f"c{i+1}"
        if recorder is not None:
            with recorder.activity("verify", claim_id, verifier_model) as verify_act:
                recorder.record_used(verify_act, f"{claim_id}_claim")
                recorder.record_used(verify_act, "source_doc")
                results = [verifier_fn(sc, chunks) for sc in dc["subclaims"]]
        else:
            results = [verifier_fn(sc, chunks) for sc in dc["subclaims"]]
        label = aggregate_label([r[0] for r in results])
        span = None
        if label != "unsupported":
            candidates = [(score, idx) for supported, score, idx in results if supported and score is not None and idx is not None]
            if candidates:
                _, best_idx = max(candidates, key=lambda c: c[0])
                span = span_from_chunk_index(
                    best_idx, full_text, sections, dc["text"],
                    max_chars=CHUNK_MAX_CHARS, section_ranges=section_ranges,
                )
            if span is None:
                span = best_span(dc["text"], sections)
        rationale = ""
        numeric_result = None
        if span is not None:
            numeric_result = check_numeric_claim(dc["text"], span["text"])
            if isinstance(numeric_result, Contradicted):
                label = "unsupported" if label == "grounded" else "partial"
                rationale = format_mismatch_rationale(dc["text"], numeric_result)
        if label == "partial" and not rationale:
            rationale = (
                "Some checkable parts of this claim were supported by the "
                "source and some were not."
            )
        if recorder is not None:
            recorder.record_generated(verify_act, f"{claim_id}_verdict", {
                "label": label,
                "numeric_check_applied": span is not None,
                "numeric_mismatch_found": isinstance(numeric_result, Contradicted),
            })
            recorder.record_generated(verify_act, f"{claim_id}_verify_signal", {
                "subclaim_results": json.dumps([
                    {"supported": supported, "score": score, "chunk_idx": idx}
                    for supported, score, idx in results
                ]),
            })
            if span is not None:
                recorder.record_derived(f"evidence_span_{span['id']}", [f"{claim_id}_verify_signal"])
        out.append({
            "id": claim_id, "text": dc["text"], "label": label,
            "evidence_span_ids": [span["id"]] if span else [],
            "quote": (span["text"][:80] if span else None),
            "page": (span["page"] if span else None),
            "rationale": rationale,
        })
    return out
